config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: "splash#index"

  resources :recipe_foods
  resources :recipes do
  resources :recipe_foods
  end
  resources :foods
  resources :users
  resources :public_recipes, only: [:index]
  
  get 'shopping_list', to: 'shopping_list#index', as: 'shopping_list'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, source: :food

  def food_quantities_by_name
    recipe_foods.joins(:food).group('foods.name').sum(:quantity)
  end

  def food_count
    foods.count
  end

  validates :name, presence: true
  validates :description, presence: true
  validates :cooking_time, presence: true
  validates :preparation_time, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user: current_user)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.recipe_foods.includes(:food)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipes_url, notice: 'Recipe was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

</div>

app/views/recipes/index.html.erb
  <%= render partial: 'devise/shared/nav' %>
<div class="container-fluid">
  <% if @recipes.empty? %>
    <div class="text-decoration-none mb-5 mx-auto d-flex justify-content-center">
      <h2 class="text-center me-6">No recipes available</h2>
      <%= link_to "Add new recipe", new_recipe_path, class: 'btn btn-secondary text-center' %>
    </div>
  <% else %>
    <h3 class="text-center mb-4">My Recipes</h3>
    <div class="text-end mb-3">
      <%= link_to "Add new recipe", new_recipe_path, class: 'btn btn-secondary' %>
    </div>
    <% @recipes.each do |recipe| %>
      <div class="card mb-4">
        <%= link_to recipe_path(recipe.id), class: 'text-decoration-none' do%>
          <div class="card-body">
            <h4 class="card-title"><%= recipe.name %></h4>
            <p class="card-text"><%= recipe.description %></p>
          </div>
        <%end%>
        <div class="card-footer bg-white text-end">
          <%= button_to "Remove", recipe_path(recipe.id), class: 'btn btn-danger', method: :delete %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/new.html.erb
  <%= render partial: 'devise/shared/nav' %>
<h1>Add New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
  <%= render partial: 'devise/shared/nav' %>
<div class="d-flex justify-content-between text-decoration-none mb-5 container">
  <div class="recipe-details">
    <h3 class="recipe-name">Name:<%= @recipe.name %> </h3>
    <p class="recipe-prep-time">Preparation Time: <%= @recipe.preparation_time%> </p>
    <p class="recipe-cooking-time">Cooking Time:<%= @recipe.cooking_time %> </p>
    <p class="recipe-description">Description:<%= @recipe.description %> </p> 
  </div>
  <div class="recipe-status">
   <% if can? :update, @recipe%>
    <% if @recipe.public %>
      <p>Current Status: Public</p>
      <%= button_to "Make private", recipe_path(@recipe), method: :patch, class: 'btn btn-dark'%>
    <% else %>
      <p>Current Status: Private</p>
      <%= button_to "Make public", recipe_path(@recipe), method: :patch, class: 'btn btn-success'%>
    <% end %>
   <% end %>
  </div>
</div>
<div class="d-flex justify-content-between text-decoration-none mb-5 container">
  <% if can? :update, @recipe%>
    <%= link_to "Generate shopping list",shopping_list_path, class: 'btn btn-secondary' %>
    <%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe.id), class: 'btn btn-secondary' %>
  <%end%>
</div>
<table class="table table-striped container">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
    <tbody>
    <% @ingredients.each do |ingredient|%>
      <tr>
          <td><%= ingredient.food.name %></td>
          <td><%= ingredient.quantity%> <%= ingredient.food.measurement_unit %></td>
          <td>$ <%= ingredient.food.price %></td>
          <td class="d-flex gap-2 justify-content-center">
          <% if can? :update, @recipe%>
            <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), class: 'modify-btn btn btn-warning' %>
            <%= button_to "Remove", recipe_recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), method: :delete, class: 'delete-btn btn btn-danger'%>
          <%else%>
            <p>Actions Not allowed</p>
          <%end%>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>