config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: "splash#index"

  resources :recipe_foods
  resources :recipes do
  resources :recipe_foods
  end
  resources :foods
  resources :users
  resources :public_recipes, only: [:index]
  
  get 'shopping_list', to: 'shopping_list#index', as: 'shopping_list'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, source: :recipe

  validates :name, presence: true, length: { maximum: 50 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { integer_only: true, greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.where(user: current_user)
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = current_user.foods.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      redirect_to foods_url, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    if @food.destroy
      flash[:notice] = 'food deleted successfully.'
    else
      flash[:error] = 'Failed to delete food.'
    end
    redirect_to foods_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> restricted this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
  <%= render partial: 'devise/shared/nav' %>
<section class="main bg-gradient-to-r from-blue-600 to-green-500 h-screen">
  <div class="container px-4 justify-center items-center mx-auto">
    
    <div class="mt-8 overflow-x-auto py-4">
      <table class="table-auto border dark-yellow-400 mx-auto w-3/5 ">
        <thead>
          <tr class="bg-gray-200">
            <th class="px-4 py-2">Food</th>
            <th class="px-4 py-2">Measurement Unit</th>
            <th class="px-4 py-2">Quantity</th>
            <th class="px-4 py-2">Unit Price</th>
            <th class="px-4 py-2">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food|%>
            <tr>
              <td class="border px-4 py-2"><%= food.name %></td>
              <td class="border px-4 py-2"><%= food.measurement_unit %></td>
              <td class="border px-4 py-2"><%= food.quantity %></td>
              <td class="border px-4 py-2"><%= food.price %></td>
              <td class="border px-4 py-2">
                <%= button_to 'Delete', food_path(food), method: :delete, data: { confirm: 'Are you sure want to delete this food?' }, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'Add Food', new_food_path, class: 'flex w-1/6 bg-yellow-500 hover:bg-yellow-700 text-white justify-center font-bold py-2 px-4 mx-auto rounded focus:outline-none focus:shadow-outline' %>
  </div>
</section>

app/views/foods/new.html.erb
  <%= render partial: 'devise/shared/nav' %>
<section class="food-section bg-gradient-to-r from-purple-500 to-indigo-600">
  <h2 class="form-header text-3xl font-bold text-white">Add New Food</h2>
  <div class="form-container bg-white shadow-md rounded-lg p-6 mt-6">
    <%= form_for @food do |f| %>
      <div class="form-group">
        <%= f.label :name, class: "form-label text-gray-700" %>
        <%= f.text_field :name, class: "form-control bg-gray-100 rounded-md py-2 px-4", required: true %>
      </div>
      <div class="form-group">
        <%= f.label :measurement_unit, class: "form-label text-gray-700" %>
        <%= f.text_field :measurement_unit, class: "form-control bg-gray-100 rounded-md py-2 px-4", required: true %>
      </div>
      <div class="form-group">
        <%= f.label :price, class: "form-label text-gray-700" %>
        <%= f.number_field :price, class: "form-control bg-gray-100 rounded-md py-2 px-4", required: true, step: "0.01" %>
      </div>
      <div class="form-group">
        <%= f.label :quantity, class: "form-label text-gray-700" %>
        <%= f.number_field :quantity, class: "form-control bg-gray-100 rounded-md py-2 px-4", required: true %>
      </div>
      <div class="form-submit">
        <%= f.submit "Create Food", class: "btn-submit btn-primary bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded-full focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</section>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>